name: Email Echo Action

on:
  workflow_dispatch:  # Allows manual trigger from Actions tab
  push:               # Also runs on push to main
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 24f2006969@ds.study.iitm.ac.in  # ✅ Display email as step name
        run: echo "Hello, world!"
